language: R
warnings_are_errors: true
sudo: true
cache: packages

addons:
    apt:
        source:
            - travic-ci/sqlite3
        packages:
            - libzip-dev
            - sqlite3
            - libsqlite3-dev
            - libsqlite3-0
            - libspatialite-dev
            - libspatialite3

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
