language: R
warnings_are_errors: true
dist: trusty
sudo: true
cache: packages

addons:
    apt:
        source:
            - travis-ci/sqlite3
        packages:
            - sqlite3
            - libsqlite3-dev
            - libsqlite3-0

r_github_packages:
    - jimhester/covr

after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e "source ('https://install-github.me/MangoTheCat/goodpractice')"
      #- Rscript -e 'library(goodpractice);gp(checks=all_checks()[grepl("(rcmdcheck|covr)",all_checks())])'
    - Rscript -e 'library(goodpractice);gp(checks=all_checks())'

